site_name: FastAPI Pagination
site_author: Yurii Karabas
site_description: FastAPI Pagination
copyright: "Copyright &copy; 2024 Yurii Karabas"
repo_url: https://github.com/uriyyo/fastapi-pagination
repo_name: uriyyo/fastapi-pagination

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  favicon: img/small-logo.png
  logo: img/small-logo.png
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  #  - 'http://localhost:8001/run_code_main.js'
  - 'https://uriyyo.github.io/mkdocs-run-code/run_code_main.js'

nav:
  - "General": index.md
  - "Learn":
      - "Pagination":
        - "General": learn/pagination/general.md
        - "Techniques": learn/pagination/techniques.md
      - "Tutorial - User Guide":
        - "First Steps": learn/tutorial_user_guide/first_steps.md
        - "Elements": learn/tutorial_user_guide/elements.md
        - "Add to Route": learn/tutorial_user_guide/add_to_route.md
        - "Own Page Model" : learn/tutorial_user_guide/own_page_model.md
        - "Items Transformer": learn/tutorial_user_guide/items_transformer.md
  - "Customization":
      - "General": customization/general.md
  - "Integrations":
      - "SQLAlchemy": integrations/sqlalchemy.md
  - "Contributing": contributing.md
  - "License": license.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uriyyo/fastapi-pagination/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/uriyyo/

watch:
  - docs
  - docs_src
  - README.md
  - mkdocs.yml
